# Generated by Django 4.1 on 2024-10-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_movie_description_alter_movie_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["title"]},
        ),
    ]
